### ISSUE TITLE
Error after recent pull of xxx

### ISSUE THREAD

**Issue by ParadingLunatic** [PurrSevere/streamdvr-docker#1]
I keep getting the following error after a build update about 5 days ago.  Looks like it's missing one/some of the plugins.

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './plugins/basic'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new Streamdvr (/app/streamdvr:31:30)
    at Object.<anonymous> (/app/streamdvr:118:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by PurrSevere** [comment]
This is because the basic.js file changed location from `./plugins/basic.js` to `./lib/plugins/basic.js.`

Update your .yml files and you'll be good to go.

**Comment by ParadingLunatic** [comment]
Thanks!  That did the trick.
